
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-29T08:23:42-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "4f8c35444020ad828cdde46a0f0064298d4b5dc5",
 "version": "1.2.1+62.g4f8c354.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
