# Dependencies derived from:
# https://github.com/nipreps/fmripost-aroma/blob/0.0.12/pyproject.toml

package:
  name: "fmripost_aroma"
  version: "0.0.12"

source:
  git_url: https://github.com/nipreps/fmripost-aroma.git
  git_rev: "0.0.12"
  patches:
    - 001-compat-nilearn-0-12-1.patch
    - 002-add-mem-gb.patch

build:
  noarch: python
  number: 6
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
  run:
    - python
    - fmriprep
    - nipype>=1.8.5
    - nireports
    - nitransforms>=24.0.2
    - niworkflows
    - sdcflows
    - smriprep
    - typer
    # Dependencies from https://github.com/nipreps/fmripost-aroma/blob/main/env.yml
    # git-annex for templateflow users with DataLad superdatasets
    - git-annex=*=alldep*
    # Base scientific python stack; required by FSL, so pinned here
    - numpy
    - scipy
    - matplotlib
    - pandas
    - h5py
    # Dependencies compiled against numpy, best to stick with conda
    - scikit-learn
    # Utilities
    - graphviz
    - pandoc
    # Workflow dependencies: FSL (versions pinned in 6.0.7.7)
    # We need SUSAN and MELODIC for ICA-AROMA
    - fsl-bet2=2111.8.*
    - fsl-melodic=2111.*
    - fsl-miscmaths=2412.4.*
    - fsl-susan=2111.0
    # Workflow dependencies: ANTs
    - ants

test:
  imports:
    - fmripost_aroma
