# -*- coding: utf-8 -*-
# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:

from .base import Spec, SpecSchema, scan_entities, entity_aliases
from .file import File, FileSchema
from .direction import PhaseEncodingDirection
from .analysis import (
    AnalysisSchema,
    Analysis,
    Variable,
    Contrast,
    Filter,
    FilterSchema,
    FixedEffectsHigherLevelAnalysisSchema,
    GLMHigherLevelAnalysisSchema,
    GroupFilterSchema,
)

from .tags import (
    Tags,
    entity_colors,
    TagsSchema,
    AnatTagsSchema,
    FuncTagsSchema,
    BoldTagsSchema,
    EventsTagsSchema,
    PEPOLARTagsSchema,
    PhaseDifferenceTagsSchema,
    Phase1TagsSchema,
    Phase2TagsSchema,
    Magnitude1TagsSchema,
    Magnitude2TagsSchema,
    FieldMapTagsSchema,
    FmapTagsSchema,
    SmoothedTagSchema,
    SmoothedTag,
    BandPassFilteredTagSchema,
    BandPassFilteredTag,
    ConfoundsRemovedTag,
    ConfoundsRemovedTagSchema,
    AtlasTagsSchema,
    SeedTagsSchema,
    MapTag,
    MapTagsSchema,
)

from .bids import (
    BIDSAnatTagsSchema,
    BIDSEventsTagsSchema,
    BIDSBoldTagsSchema,
    BIDSFmapTagsSchema,
)

__all__ = [
    Spec,
    SpecSchema,
    scan_entities,
    entity_aliases,
    File,
    FileSchema,
    Tags,
    entity_colors,
    TagsSchema,
    AnatTagsSchema,
    FuncTagsSchema,
    BoldTagsSchema,
    EventsTagsSchema,
    PEPOLARTagsSchema,
    PhaseDifferenceTagsSchema,
    Phase1TagsSchema,
    Phase2TagsSchema,
    Magnitude1TagsSchema,
    Magnitude2TagsSchema,
    FieldMapTagsSchema,
    FmapTagsSchema,
    SmoothedTagSchema,
    SmoothedTag,
    BandPassFilteredTagSchema,
    BandPassFilteredTag,
    ConfoundsRemovedTag,
    ConfoundsRemovedTagSchema,
    AtlasTagsSchema,
    SeedTagsSchema,
    MapTag,
    MapTagsSchema,
    BIDSAnatTagsSchema,
    BIDSEventsTagsSchema,
    BIDSBoldTagsSchema,
    BIDSFmapTagsSchema,
    PhaseEncodingDirection,
    AnalysisSchema,
    Analysis,
    Variable,
    Contrast,
    Filter,
    FilterSchema,
    FixedEffectsHigherLevelAnalysisSchema,
    GLMHigherLevelAnalysisSchema,
    GroupFilterSchema,
]
