{% set name = "pytest-textual-snapshot" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_textual_snapshot-{{ version }}.tar.gz
  sha256: 065217055ed833b8a16f2320a0613f39a0154e8d9fee63535f29f32c6414b9d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0.0
    - pytest >=8.0.0
    - rich >=12.0.0
    - textual >=0.28.0
    - syrupy >=4.0.0
    - jinja2 >=3.0.0

test:
  imports:
    - pytest_textual_snapshot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/darrenburns/pytest-textual-snapshot
  summary: Snapshot testing for Textual apps
  license: MIT
  license_file: LICENSE
