{% set platform = target_platform or 'unknown' %}

package:
  name: rmath
  version: 4.3.1 #4.2.0

source:
  url: https://cran.r-project.org/src/base/R-4/R-4.3.1.tar.gz

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - make
    - python 3.11.*
    - libzlib >=1.2.13,<1.3.0a0

  host:
    - python 3.11.*
    - bzip2
    - curl
    - pcre2
    - xz
    - zlib
    - libzlib >=1.2.13,<1.3.0a0

  run: []

test:
  commands:
    {% if platform.startswith("osx") %}
    - test -f ${PREFIX}/lib/libRmath.dylib  # testing on macOS
    {% else %}
    - test -f ${PREFIX}/lib/libRmath.so     # testing on Linux and others
    {% endif %}
    - test -f ${PREFIX}/include/Rmath.h

about:
  home: http://www.r-project.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'GNU R standalone mathematics library.'
