[build-system]
# keep in sync with requirements.in
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel"]

[tool.isort]
profile = "black"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
