# -*- coding: utf-8 -*-

import numpy as np

font = {
    " ": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "!": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    '"': np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "#": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, False, True, False, False],
            [True, True, True, True, True, False],
            [True, True, True, True, True, False],
            [False, True, False, True, False, False],
            [False, True, False, True, False, False],
            [True, True, True, True, True, False],
            [True, True, True, True, True, False],
            [False, True, False, True, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "$": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "%": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, False, False, False],
            [True, False, True, False, False, True],
            [True, True, True, False, True, False],
            [False, False, False, True, False, False],
            [False, False, True, False, False, False],
            [False, True, False, True, True, True],
            [True, False, False, True, False, True],
            [False, False, False, True, True, True],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "&": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, False, False],
            [True, True, False, True, False, False],
            [True, True, False, True, False, False],
            [False, True, True, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, False, False],
            [True, True, False, True, True, False],
            [True, True, True, False, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "'": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "(": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, True, True, False],
            [False, False, True, True, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, True, False, False],
            [False, False, False, True, True, False],
            [False, False, False, False, False, False],
        ]
    ),
    ")": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, True, True, False, False, False],
            [True, True, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "*": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, True, False, False, False],
            [True, True, True, True, True, False],
            [False, True, True, True, False, False],
            [True, True, True, True, True, False],
            [False, False, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "+": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [True, True, True, True, True, True],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    ",": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, False, False, False],
            [False, True, False, False, False, False],
        ]
    ),
    "-": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    ".": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "/": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, True, True],
            [False, False, False, False, True, True],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "0": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "1": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, True, True, False, False],
            [False, True, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "2": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "3": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "4": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "5": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "6": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "7": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "8": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, True, True, True, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "9": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    ":": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    ";": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, False, False, False],
            [False, True, False, False, False, False],
        ]
    ),
    "<": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, True, True, False],
            [False, False, True, True, False, False],
            [False, True, True, False, False, False],
            [True, True, False, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, True, False, False],
            [False, False, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "=": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    ">": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, True, False, False],
            [False, False, False, True, True, False],
            [False, False, True, True, False, False],
            [False, True, True, False, False, False],
            [True, True, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "?": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, True, True, True, True, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "@": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
        ]
    ),
    "A": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "B": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, False, False],
            [True, True, False, True, False, False],
            [True, True, False, True, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "C": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "D": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "E": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "F": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "G": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, False, True, False],
            [True, True, False, False, True, False],
            [True, True, False, False, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "H": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "I": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, True, True, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "J": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "K": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, False, False],
            [True, True, True, True, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "L": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "M": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, True, True, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "N": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "O": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "P": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "Q": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, True, True],
            [False, False, False, False, False, False],
        ]
    ),
    "R": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, True, True, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "S": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "T": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, True],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "U": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "V": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, True, True, True, False, False],
            [False, False, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "W": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, True, True, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "X": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, True, True, True, False, False],
            [False, True, True, True, False, False],
            [False, True, True, True, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "Y": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, True, True],
            [True, True, False, False, True, True],
            [True, True, False, False, True, True],
            [True, True, True, True, True, True],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "Z": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, True, True, False, False],
            [False, True, True, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "[": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, True, True, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, True, True, False],
            [False, False, False, False, False, False],
        ]
    ),
    "\\": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, False, True, True],
            [False, False, False, False, True, True],
            [False, False, False, False, False, False],
        ]
    ),
    "]": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [True, True, True, True, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "^": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, True, False, False, False],
            [False, True, True, True, False, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "_": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
        ]
    ),
    "`": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, False, False, False, False],
            [False, True, True, False, False, False],
            [False, False, True, True, False, False],
            [False, False, False, True, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "a": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "b": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "c": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "d": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "e": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "f": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, True, True, False],
            [False, True, True, False, False, False],
            [True, True, True, True, True, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "g": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
        ]
    ),
    "h": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "i": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "j": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
        ]
    ),
    "k": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, True, True, False, False],
            [True, True, True, False, False, False],
            [True, True, True, True, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "l": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "m": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, True, True, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "n": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "o": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "p": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
        ]
    ),
    "q": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
        ]
    ),
    "r": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [True, True, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "s": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "t": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [True, True, True, True, True, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "u": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "v": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, True, True, True, False, False],
            [False, False, True, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "w": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, False, True, False, True, False],
            [True, True, True, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "x": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, True, True, True, False, False],
            [False, True, True, True, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "y": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, False, True, True, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [True, True, True, True, True, False],
        ]
    ),
    "z": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, True, True, False],
            [False, False, True, True, False, False],
            [False, True, True, False, False, False],
            [True, True, False, False, False, False],
            [True, True, True, True, True, False],
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "{": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, True, True, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [True, True, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, True, True, False],
            [False, False, False, False, False, False],
        ]
    ),
    "|": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, True, True, False, False, False],
            [False, False, False, False, False, False],
        ]
    ),
    "}": np.array(
        [
            [False, False, False, False, False, False],
            [False, False, False, False, False, False],
            [True, True, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, False, True, True, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [False, False, True, True, False, False],
            [True, True, True, True, False, False],
            [False, False, False, False, False, False],
        ]
    ),
}
