package:
  name: "smriprep"
  version: "0.7.2+halfpipe.2"

source:
  git_url: https://github.com/HippocampusGirl/smriprep.git
  git_rev: "0.7.2+halfpipe.2"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

# Requirements derived from
# https://github.com/HippocampusGirl/smriprep/blob/halfpipe/setup.cfg
requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python 3.11.*
    - indexed_gzip>=0.8.8
    - lockfile
    - matplotlib>=2.2.0
    - nibabel>=3.0.1
    - nipype # local
    - niworkflows # local
    - numpy
    - packaging
    - pybids>=0.11.1
    - pyyaml
    - templateflow>=0.6 # local
test:
  imports:
    - smriprep

about:
  home: https://www.nipreps.org/smriprep/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "sMRIprep - a robust and easy-to-use pipeline for preprocessing of structural magnetic resonance images (MRI) of the brain."
