# Dependencies derived from:
# https://github.com/nipy/nitransforms/blob/25.0.1/pyproject.toml

package:
  name: nitransforms
  version: "25.0.1"

source:
  url: https://files.pythonhosted.org/packages/source/n/nitransforms/nitransforms-25.0.1.tar.gz
  sha256: eae9e6afd8960a65f4b9be95af47798301f87dd8cecac50a94a05b3b4052583c

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy>=2.1
    - scipy>=1.8
    - h5py>=3.11
    - nibabel>=5.2

test:
  imports:
    - nitransforms

about:
  home: https://github.com/nipy/nitransforms
  summary: 'A development repo for nipy/nibabel#656'
