{% set name = "nitransforms" %}
{% set version = "24.1.1" %}

# Dependencies derived from:
# https://github.com/nipy/nitransforms/blob/24.1.1/pyproject.toml

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 536956c580ee03e3e93043208da9eafc920b5934c7e7e0c4c7d759fca0963633

build:
  number: 0
  script: {{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -vv

requirements:
  host:
    - pip
    - python 3.11.*
  run:
    - python 3.11.*
    - numpy>=1.21
    - scipy>=1.8
    - h5py>=3.9
    - nibabel>=4.0

test:
  imports:
    - nitransforms

about:
  home: https://github.com/nipy/nitransforms
  summary: 'A development repo for nipy/nibabel#656'
