# Dependencies derived from:
# https://github.com/nipy/nitransforms/blob/24.1.1/pyproject.toml

package:
  name: nitransforms
  version: "24.1.1"

source:
  url: https://files.pythonhosted.org/packages/source/n/nitransforms/nitransforms-24.1.1.tar.gz
  sha256: 536956c580ee03e3e93043208da9eafc920b5934c7e7e0c4c7d759fca0963633

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy>=1.21
    - scipy>=1.8
    - h5py>=3.9
    - nibabel>=4.0

test:
  imports:
    - nitransforms

about:
  home: https://github.com/nipy/nitransforms
  summary: 'A development repo for nipy/nibabel#656'
