{% set name = "pybtex-apa-style" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybtex-apa-style-{{ version }}.tar.gz
  sha256: 38a6d11e8f40f259b1d0a6974b6dbae93edbe009c247d83de14c26bdd965afb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - formatting
    - labels
    - names
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/naeka/pybtex-apa-style
  summary: Pybtex APA-like style

extra:
  recipe-maintainers:
    - HippocampusGirl
