{% set name = "pybids" %}
{% set version = "0.14.1" %}

# note to future developer: pybids repo has its own conda recipes from
# version 0.15.6 onwards. When hitting that specification, transition to theirs
# and this can be deleted.
# Reference: https://github.com/conda-forge/pybids-feedstock/blob/5e9bf942522932876711464a06a95ddbc9981095/recipe/meta.yaml

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybids-{{ version }}.tar.gz
  sha256: fb32354a9e7230d9893ac99c78ef697cf921f03bc3e745b725488fc49b06f491

build:
  entry_points:
    - pybids=bids.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0,!=61.0.0
  run:
    - bids-validator
    - click >=8.0
    - formulaic >=0.2.4
    - nibabel >=2.1
    - num2words
    - numpy
    - pandas >=0.23
    - python >=3.7
    - scipy
    - sqlalchemy <1.4.0.dev0

test:
  imports:
    - bids
  commands:
    - pybids --help
  requires:
    - pip

about:
  home: http://github.com/bids-standard/pybids
  summary: 'bids: interface with datasets conforming to BIDS'
  license: MIT
  license_file:
    - LICENSE
