# Requirements derived from
# https://github.com/nipreps/smriprep/blob/0.19.2/pyproject.toml

package:
  name: "smriprep"
  version: "0.19.2"

source:
  url: https://files.pythonhosted.org/packages/source/s/smriprep/smriprep-0.19.2.tar.gz
  sha256: 843c2646764f92ebb824fe6da9ce809dcbac801c8d5f4fd19784450a1c31f963

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - acres>=0.2
    - indexed_gzip>=1.7
    - lockfile>=0.12.2
    - looseversion>=1.3.0
    - matplotlib>=3.5
    - nibabel>=4.0.1
    - nipype>=1.8.5
    - nireports>=25.3.0
    - niworkflows>=1.14.0
    - numpy>=1.24
    - packaging>=24
    - pybids>=0.16
    - pyyaml>=6.0
    - templateflow>=25.0
test:
  imports:
    - smriprep

about:
  home: https://www.nipreps.org/smriprep/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "sMRIprep - a robust and easy-to-use pipeline for preprocessing of structural magnetic resonance images (MRI) of the brain."
