# Dependencies derived from:
# https://github.com/nipreps/sdcflows/blob/2.15.0/pyproject.toml

package:
  name: "sdcflows"
  version: "2.15.0"

source:
  url: https://files.pythonhosted.org/packages/source/s/sdcflows/sdcflows-2.15.0.tar.gz
  sha256: f1fa31be1f3208c2f616c3f5c0cbbede43a9a0c676ae561932f284294fe4c0ab

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - nipreps-versions
  run:
    - python
    - acres>=0.5
    - attrs>=20.1.0
    - nibabel>=5.1.1
    - nipype>=1.9.0
    - migas>=0.4.0
    - nireports>=25.0.1
    - niworkflows>=1.14.2
    - nitransforms>=25.0.1
    - numpy>=2.0
    - pybids>=0.16.4
    - scikit-image>=0.23
    - scipy>=1.10
    - templateflow>=23.1
    - toml>=0.10

test:
  imports:
    - sdcflows

about:
  home: https://github.com/nipreps/sdcflows
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Susceptibility Distortion Correction Flows - a toolbox for preprocessing magnetic resonance images of the brain."
