# Dependencies derived from:
# https://github.com/nipreps/sdcflows/blob/2.13.0/pyproject.toml

package:
  name: "sdcflows"
  version: "2.13.0"

source:
  git_url: https://github.com/nipreps/sdcflows.git
  git_rev: "2.13.0"

build:
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - nipreps-versions
  run:
    - python
    - acres>=0.2
    - attrs>=20.1.0
    - nibabel>=3.0
    - nipype>=1.8.5
    - migas>=0.4.0
    - niworkflows>=1.7.0
    - nitransforms>=24.1.0
    - numpy>=1.23
    - pybids>=0.16.4
    - scikit-image>=0.18
    - scipy>=1.8.1
    - templateflow>=23.1
    - toml>=0.10

test:
  imports:
    - sdcflows

about:
  home: https://github.com/nipreps/sdcflows
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Susceptibility Distortion Correction Flows - a toolbox for preprocessing magnetic resonance images of the brain."
