package:
  name: gica_cmd
  version: unknown

source:
  git_url: https://github.com/trendscenter/gift.git

build:
  number: 4
  rpaths:
    - lib/mcr/bin/glnxa64/
    - lib/mcr/cefclient/sys/os/glnxa64/
    - lib/mcr/runtime/glnxa64/
    - lib/mcr/sys/java/jre/glnxa64/jre/lib/amd64/
    - lib/mcr/sys/java/jre/glnxa64/jre/lib/amd64/server/
    - lib/mcr/sys/opengl/lib/glnxa64/
    - lib/mcr/sys/os/glnxa64/
    - lib/
    - lib/jvm/lib/
  script_env:
   - DOCKER_HOST

requirements:
  build:
    - docker-cli
  host:
    - matlab-runtime
  run:
    - matlab-runtime
