package:
  name: "tedana"
  version: "0.0.9a1"

source:
  url: https://github.com/ME-ICA/tedana/archive/refs/tags/0.0.9a1.tar.gz
  sha256: 51cb8456349d6ee8806c32699649dd7f7d86c011ef7adac12e36719c82d4094c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

# Dependencies derived from:
# https://github.com/ME-ICA/tedana/blob/0.0.9a1/requirements.txt
requirements:
  host:
    - pip
    - python 3.11.*
  run:
    - python 3.11.*
    - duecredit
    - matplotlib
    - nibabel>=2.5.1
    - nilearn>=0.5.2
    - numpy>=1.15
    - pandas
    - scikit-learn>=0.22
    - scipy>=1.3.3
    - threadpoolctl

test:
  imports:
    - tedana

about:
  home: https://github.com/ME-ICA/tedana
  summary: "tedana is a Python library for denoising multi-echo fMRI data"
