package:
  name: rmath
  version: 4.4.1

source:
  url: https://cran.r-project.org/src/base/R-4/R-4.4.1.tar.gz
  sha256: b4cb675deaaeb7299d3b265d218cde43f192951ce5b89b7bb1a5148a36b2d94d

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - make
  host:
    - bzip2
    - curl
    - pcre2
    - xz
    - zlib
  run: []

test:
  commands:
    - test -f ${PREFIX}/lib/libRmath.dylib # [osx]
    - test -f ${PREFIX}/lib/libRmath.so # [linux]
    - "test -f ${PREFIX}/include/Rmath.h"

about:
  home: http://www.r-project.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: "GNU R standalone mathematics library."
