# Dependencies derived from:
# https://github.com/nipreps/migas-py/blob/main/pyproject.toml

package:
  name: "migas"
  version: "0.4.0"

source:
  url: https://files.pythonhosted.org/packages/source/m/migas/migas-0.4.0.tar.gz
  sha256: 069481021e86fb9a84b9977f2f5adb9c77c5220787065859b9510cf80e7095f5

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs

  run:
    - python
    - hatchling
    - hatch-vcs
    - ci-info

test:
  imports:
    - migas

about:
  home: https://github.com/nipreps/migas-py
  summary: "A Python package to communicate with a migas server."
