{% set name = "niworkflows" %}
{% set version = "1.13.4" %}

# Dependencies derived from:
# https://github.com/nipreps/niworkflows/blob/maint/1.13.4/pyproject.toml

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2bec7ab4e68a4761e4abb83cccb578388cfc253be55976832e4e7b299e485dfd

build:
  number: 0
  script: {{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v

requirements:
  host:
    - python 3.11.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python 3.11.*
    - acres
    - attrs>=20.1
    - jinja2>=3
    - looseversion
    - matplotlib>=3.5
    - nibabel>=3.0
    - nilearn>=0.8
    - nipype>=1.8.5
    - nitransforms>=22.0.0
    - numpy>=1.20
    - packaging
    - pandas>=1.2
    - pybids>=0.15.1
    - PyYAML>=5.4
    - scikit-image>=0.18
    - scipy>=1.8
    - seaborn>=0.11
    - svgutils>=0.3.4  # https://github.com/nipreps/niworkflows/issues/595
    - templateflow>=23.1
    - transforms3d>=0.4

test:
  imports:
    - niworkflows

about:
  home: https://github.com/nipreps/niworkflows
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "NeuroImaging Workflows provides processing tools for magnetic resonance images of the brain."
