# Dependencies derived from:
# https://github.com/nipreps/niworkflows/blob/1.14.2/pyproject.toml

package:
  name: "niworkflows"
  version: "1.14.2"

source:
  url: https://pypi.io/packages/source/n/niworkflows/niworkflows-1.14.2.tar.gz
  sha256: 9f72aae8610e2517078c2b937d80381410ac3d876db9a141c0c9a17416a08a60

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - acres
    - attrs>=20.1
    - jinja2>=3
    - looseversion
    - matplotlib>=3.5
    - nibabel>=3.0
    - nilearn>=0.8
    - nipype>=1.8.5
    - nitransforms>=22.0.0
    - numpy>=1.20
    - packaging
    - pandas>=1.2
    - pybids>=0.15.1
    - PyYAML>=5.4
    - scikit-image>=0.18
    - scipy>=1.8
    - seaborn>=0.11
    - svgutils>=0.3.4 # https://github.com/nipreps/niworkflows/issues/595
    - templateflow>=23.1
    - transforms3d>=0.4

test:
  imports:
    - niworkflows

about:
  home: https://github.com/nipreps/niworkflows
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "NeuroImaging Workflows provides processing tools for magnetic resonance images of the brain."
