{% set name = "tzdata" %}
{% set version = "2023.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/70/e5/81f99b9fced59624562ab62a33df639a11b26c582be78864b339dafa420d/{{ name }}-{{ version }}.tar.gz
  sha256: 11ef1e08e54acb0d4f95bdb1be05da659673de4acbd21bf9c69e94cc5e907a3a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - tzdata

about:
  home: https://pypi.org/project/tzdata/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Provider of IANA time zone data'
