# Dependencies derived from:
# https://github.com/nipreps/nireports/blob/main/pyproject.toml

package:
  name: "nireports"
  version: "25.2.0"

source:
  git_url: https://github.com/nipreps/nireports.git
  git_rev: "25.2.0"

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - nipreps-versions
  run:
    - python
    - acres>=0.2
    - matplotlib>=3.5
    - nibabel>=3.0.1
    - nilearn>=0.8
    - nipype>=1.8.5
    - numpy>=1.20
    - pandas>=1.2
    - pybids>=0.15.1
    - pyyaml>=5.4
    - seaborn>=0.13
    - templateflow>=23.1
    - lxml>=4.6 # required by vendored svgutils

test:
  imports:
    - nireports
