# Dependencies derived from:
# https://github.com/nipreps/nireports/blob/25.3.0/pyproject.toml

package:
  name: "nireports"
  version: "25.3.0"

source:
  url: https://files.pythonhosted.org/packages/source/n/nireports/nireports-25.3.0.tar.gz
  sha256: 0ac04950b3727cdc1e2740a9cb1a63aa047b24e2c7a1d945a0f852bfe753d879

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - nipreps-versions
  run:
    - python
    - acres>=0.2
    - matplotlib>=3.6
    - nibabel>=5.0
    - nilearn>=0.10.1
    - nipype>=1.8.5
    - numpy>=1.24
    - pandas>=1.5
    - pybids>=0.15.1
    - pyyaml>=6.0
    - seaborn>=0.13
    - templateflow>=23.1
    - lxml>=4.7 # required by vendored svgutils

test:
  imports:
    - nireports
