{% set version = "0.0.9a1" %}
{% set name = "tedana" %}

# Dependencies derived from:
# https://github.com/ME-ICA/tedana/blob/0.0.9a1/requirements.txt

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c79b0d8b52171db403fb8c4bd15b147f61a6c91fd239b342819640e20118bf6

build:
  number: 0
  script: {{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v

requirements:
  host:
    - pip
    - python 3.11.*
  run:
    - python 3.11.*
    - duecredit
    - matplotlib
    - nibabel>=2.5.1
    - nilearn>=0.5.2
    - numpy>=1.15
    - pandas
    - scikit-learn>=0.22
    - scipy>=1.3.3
    - threadpoolctl


test:
  imports:
    - tedana

about:
  home: https://github.com/ME-ICA/tedana
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'tedana is a Python library for denoising multi-echo fMRI data'
