{% set name = "tedana" %}
{% set version = "25.0.1" %}

# Dependencies derived from:
# https://github.com/ME-ICA/tedana/blob/25.0.1/pyproject.toml

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b85742f83f7c853dc709cae8c9aa37f34fd964971fe986296861ad5286c4ccfa

build:
  number: 0
  script: {{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v

requirements:
  host:
    - pip
    - python 3.11.*
    - hatchling
    - hatch-vcs
  run:
    - python 3.11.*
    - hatchling
    - bokeh>=1.0.0
    - mapca>=0.0.4
    - matplotlib
    - nibabel>=2.5.1
    - nilearn>=0.10.3
    - numpy>=1.16
    - pandas>=2.0
    - pybtex
    - pybtex-apa-style
    - robustica>=0.1.4
    - scikit-learn>=0.21
    - scipy>=1.2.0
    - seaborn
    - threadpoolctl
    - tqdm

test:
  imports:
    - tedana

about:
  home: https://github.com/ME-ICA/tedana
  summary: 'tedana is a Python library for denoising multi-echo fMRI data'
