import pytest
from pathlib import Path

from halfpipe.ingest.database import Database
from halfpipe.collect.bold import collect_bold_files
from halfpipe.workflows.post_processing.factory import PostProcessingFactory


def test_init(mock_post_processing_factory):
    """ Check postprocessing_factory fixture creation."""
    assert isinstance(mock_post_processing_factory, PostProcessingFactory)

def test_setup(
    mock_spec, 
    bids_data, 
    mock_fmriprep_factory,
    mock_post_processing_factory
    ):
    """ Check that setup works with test data."""
    database = Database(mock_spec, bids_database_dir=bids_data)
    bold_file_paths_dict = collect_bold_files(mock_spec, database)

    # this weird thing is to make sure we're passing the right path (path generated by conftest fixture without the ending folder 'rawdata')
    mock_fmriprep_factory.setup(Path(str(bids_data)[:-8]), set(bold_file_paths_dict.keys()))

    mock_post_processing_factory.setup(bold_file_paths_dict)

    # TODO what to check w assert?