# Dependencies derived from:
# https://github.com/nipreps/fmriprep/blob/master/pyproject.toml

package:
  name: "fmriprep"
  version: "24.1.x"

source:
  git_url: https://github.com/nipreps/fmriprep.git
  git_rev: "f81a3040e9c351946459703e4683cc74c8fe9f54"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python 3.11.*
    - pip
    - hatchling
    - hatch-vcs
    - nipreps-versions
  run:
    - python 3.11.*
    - acres>=0.2
    - looseversion>=1.3
    - nipype>=1.8.5
    - nibabel>=4.0.1
    - nireports>=24.1.0
    - nitime>=0.9
    - nitransforms>=24.1.1
    - niworkflows>=1.12.2
    - numpy>=1.24
    - packaging>=24
    - pandas>=1.2
    - psutil>=5.4
    - pybids>=0.16
    - requests>=2.27
    - sdcflows>=2.11.0
    - smriprep>=0.17.0
    - tedana>=23.0.2
    - templateflow>=24.2.2
    - transforms3d>=0.4
    - toml>=0.10
    - codecarbon>=2
    - APScheduler>=3.10
    - fsl-bet2=2111.4
    - fsl-flirt=2111.2
    - fsl-fast4=2111.3
    - fsl-fugue=2201.3
    - fsl-mcflirt=2111.0
    - fsl-miscmaths=2203.2
    - fsl-topup=2203.2

test:
  imports:
    - fmriprep
    - fmriprep.cli.parser
    - fmriprep.cli.run
    - fmriprep.cli.version
    - fmriprep.cli.workflow
    - fmriprep._warnings
    - fmriprep.utils.meepi
    - fmriprep.utils.telemetry
    - fmriprep.utils.misc
    - fmriprep.utils.confounds
    - fmriprep.utils.bids
    - fmriprep.utils.debug
    - fmriprep.interfaces.patches
    - fmriprep.interfaces.multiecho
    - fmriprep.interfaces.reports
    - fmriprep.interfaces.confounds
    - fmriprep.interfaces.gifti
    - fmriprep.interfaces.workbench
    - fmriprep.interfaces.maths
    - fmriprep.config
    - fmriprep.workflows.bold.confounds
    - fmriprep.workflows.bold.resampling
    - fmriprep.workflows.bold.base
    - fmriprep.workflows.bold.t2s
    - fmriprep.workflows.bold.registration
    - fmriprep.workflows.bold.hmc
    - fmriprep.workflows.bold.outputs
    - fmriprep.workflows.bold.stc
    - fmriprep.workflows.base
    - fmriprep.reports.core

about:
  home: https://www.nipreps.org/fmriprep/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "fMRIprep - a robust and easy-to-use pipeline for preprocessing of functional magnetic resonance images (fMRI) of the brain."
