# Dependencies derived from:
# https://github.com/nipreps/fmriprep/blob/25.1.1/pyproject.toml
# https://github.com/nipreps/fmriprep/blob/25.1.1/env.yml

package:
  name: "fmriprep"
  version: "25.2.3"

source:
  url: https://pypi.io/packages/source/f/fmriprep/fmriprep-25.2.3.tar.gz
  sha256: 58d885e257f0cc9664750384a7586a2ed8e666f9680b5b8199087675c640098a

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - nipreps-versions
  run:
    - python
    - acres>=0.2
    - looseversion>=1.3
    - nibabel>=5.1.1
    - nipype>=1.9.0
    - nireports>=24.1.0
    - nitime=0.11.*
    - nitransforms>=25.0.1
    - niworkflows>=1.14.2
    - numpy=2.2.*
    - packaging>=24
    - pandas=2.2.*
    - psutil>=5.4
    - pybids>=0.16
    - requests>=2.27
    - sdcflows>=2.15.0
    - smriprep>=0.19.2
    - tedana>=25.0.0
    - templateflow>=24.2.2
    - transforms3d>=0.4.2
    - toml>=0.10
    - codecarbon>=2
    - APScheduler>=3.10
    - scipy=1.15.*
    - matplotlib=3.10.*
    - h5py=3.13.*
    - scikit-image=0.25.*
    - scikit-learn=1.6.*
    - graphviz=12.2.*
    - pandoc=3.7.*
    # Workflow dependencies: AFNI
    - afni-3dtshift
    - afni-3dunifize
    # Workflow dependencies: ANTs
    - ants=2.6.*
    # Workflow dependencies: Convert3d
    - convert3d=1.4
    # Workflow dependencies: Connectome Workbench
    - connectome-workbench-cli=2.0.*=*qt6*
    # Workflow dependencies: FSL (versions pinned in 6.0.7.13)
    - fsl-bet2=2111.8.*
    - fsl-flirt=2111.4.*
    - fsl-fast4=2111.3.*
    - fsl-fugue=2201.5.*
    - fsl-mcflirt=2111.0.*
    - fsl-miscmaths=2412.4.*
    - fsl-topup=2203.5.*

test:
  imports:
    - fmriprep
    - fmriprep.cli.parser
    - fmriprep.cli.run
    - fmriprep.cli.version
    - fmriprep.cli.workflow
    - fmriprep._warnings
    - fmriprep.utils.meepi
    - fmriprep.utils.telemetry
    - fmriprep.utils.misc
    - fmriprep.utils.confounds
    - fmriprep.utils.bids
    - fmriprep.utils.debug
    - fmriprep.interfaces.patches
    - fmriprep.interfaces.multiecho
    - fmriprep.interfaces.reports
    - fmriprep.interfaces.confounds
    - fmriprep.interfaces.gifti
    - fmriprep.interfaces.workbench
    - fmriprep.interfaces.maths
    - fmriprep.config
    - fmriprep.workflows.bold.confounds
    - fmriprep.workflows.bold.resampling
    - fmriprep.workflows.bold.base
    - fmriprep.workflows.bold.t2s
    - fmriprep.workflows.bold.registration
    - fmriprep.workflows.bold.hmc
    - fmriprep.workflows.bold.outputs
    - fmriprep.workflows.bold.stc
    - fmriprep.workflows.base
    - fmriprep.reports.core

about:
  home: https://www.nipreps.org/fmriprep/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "fMRIprep - a robust and easy-to-use pipeline for preprocessing of functional magnetic resonance images (fMRI) of the brain."
