{% set version = "1.3.24" %}

package:
  name: sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SQLAlchemy/SQLAlchemy-{{ version }}.tar.gz
  sha256: ebbb777cbf9312359b897bf81ba00dae0f5cb69fba2a18265dcc18a6f5ef7519

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -v

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - mock  # [py27]
  imports:
    - sqlalchemy
    - sqlalchemy.connectors
    - sqlalchemy.databases
    - sqlalchemy.dialects
    - sqlalchemy.dialects.firebird
    - sqlalchemy.dialects.mssql
    - sqlalchemy.dialects.mysql
    - sqlalchemy.dialects.oracle
    - sqlalchemy.dialects.postgresql
    - sqlalchemy.dialects.sqlite
    - sqlalchemy.dialects.sybase
    - sqlalchemy.engine
    - sqlalchemy.event
    - sqlalchemy.ext
    - sqlalchemy.ext.declarative
    - sqlalchemy.orm
    - sqlalchemy.sql
    - sqlalchemy.testing
    - sqlalchemy.testing.plugin
    - sqlalchemy.util

about:
  home: http://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: Database Abstraction Library.
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: http://docs.sqlalchemy.org/en/rel_1_0/
  dev_url: https://bitbucket.org/zzzeek/sqlalchemy/
  doc_source_url: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/index.rst
