{% set name = "fmriprep" %}
{% set version = "20.2.7+halfpipe.2" %}

# Dependencies derived from:
# https://github.com/HippocampusGirl/fmriprep/blob/halfpipe/setup.cfg#L25C5-L43C9

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/HippocampusGirl/fmriprep.git
  git_rev: "{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python 3.11.*
    - nipype
    - indexed_gzip>=0.8.8
    - networkx #==2.5.0
    - nibabel>=3.0
    - nipype>=1.5.1
    - nilearn=0.10.2 #~=0.6.2
    - nitime
    - nitransforms # >= 20.0.0rc3, < 20.2
    - niworkflows #~= 1.3.5
    - numpy
    - pandas
    - psutil>=5.4
    - pybids>=0.12.1
    - pyyaml
    - requests
    - sdcflows #~=1.3.2
    - smriprep #~=0.7.2
    - tedana==0.0.9a1
    - templateflow >=0.6
    - toml

test:
  imports:
    - fmriprep
    - fmriprep.__about__
    - fmriprep.cli.parser
    - fmriprep.cli.run
    - fmriprep.cli.version
    - fmriprep.cli.workflow
    - fmriprep._warnings
    - fmriprep.utils.meepi
    # - fmriprep.utils.telemetry
    - fmriprep.utils.misc
    - fmriprep.utils.confounds
    - fmriprep.utils.bids
    # - fmriprep.utils.debug
    - fmriprep.interfaces.patches
    - fmriprep.interfaces.multiecho
    - fmriprep.interfaces.reports
    - fmriprep.interfaces.confounds
    # - fmriprep.interfaces.gifti
    # - fmriprep.interfaces.workbench
    # - fmriprep.interfaces.maths
    - fmriprep.config
    - fmriprep.workflows.bold.confounds
    - fmriprep.workflows.bold.resampling
    - fmriprep.workflows.bold.base
    - fmriprep.workflows.bold.t2s
    - fmriprep.workflows.bold.registration
    - fmriprep.workflows.bold.hmc
    - fmriprep.workflows.bold.outputs
    - fmriprep.workflows.bold.stc
    - fmriprep.workflows.base
    - fmriprep.reports.core

about:
  home: https://www.nipreps.org/fmriprep/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "fMRIprep - a robust and easy-to-use pipeline for preprocessing of functional magnetic resonance images (fMRI) of the brain."
