{% set name = "fmriprep" %}
{% set version = "20.2.7+halfpipe.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/HippocampusGirl/fmriprep.git
  git_rev: "{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -v"

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python 3.11.*

test:
  imports:
    - fmriprep
    - fmriprep.__about__
    - fmriprep.cli.parser
    - fmriprep.cli.run
    - fmriprep.cli.version
    - fmriprep.cli.workflow
    - fmriprep._warnings
    - fmriprep.utils.meepi
    - fmriprep.utils.telemetry
    - fmriprep.utils.misc
    - fmriprep.utils.confounds
    - fmriprep.utils.bids
    - fmriprep.utils.debug
    - fmriprep.interfaces.patches
    - fmriprep.interfaces.workbench
    - fmriprep.interfaces.maths
    - fmriprep.interfaces.multiecho
    - fmriprep.interfaces.gifti
    - fmriprep.interfaces.reports
    - fmriprep.interfaces.confounds
    - fmriprep.config
    - fmriprep.workflows.bold.confounds
    - fmriprep.workflows.bold.resampling
    - fmriprep.workflows.bold.base
    - fmriprep.workflows.bold.t2s
    - fmriprep.workflows.bold.registration
    - fmriprep.workflows.bold.hmc
    - fmriprep.workflows.bold.outputs
    - fmriprep.workflows.bold.stc
    - fmriprep.workflows.base
    - fmriprep.reports.core

about:
  home: https://www.nipreps.org/fmriprep/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "fMRIprep - a robust and easy-to-use pipeline for preprocessing of functional magnetic resonance images (fMRI) of the brain."
