# Dependencies derived from:
# https://github.com/ME-ICA/mapca/blob/main/pyproject.toml

package:
  name: "mapca"
  version: "0.0.6"

source:
  url: https://files.pythonhosted.org/packages/source/m/mapca/mapca-0.0.6.tar.gz
  sha256: 38c727c779e1868c0b17a95777004a5a28076aab40e51e50d972db0a26decf25

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
  run:
    - python
    - hatchling
    - nibabel>=2.5.1
    - nilearn
    - numpy>=1.16
    - scikit-learn>=1.2
    - scipy>=1.3.3

test:
  requires:
    - python
  imports:
    - mapca
    - mapca.utils
    - mapca.mapca

about:
  home: https://github.com/ME-ICA/mapca
  summary: "Moving Average Principal Component Analysis for fMRI data"
