Bootstrap: docker
From: halfpipe/halfpipe:latest

%environment
  export HALFPIPE_RESOURCE_DIR="/home/fmriprep/.cache/halfpipe"
  export TEMPLATEFLOW_HOME="/home/fmriprep/.cache/templateflow"

%setup
  mkdir -p ${SINGULARITY_ROOTFS}/halfpipe
  mkdir -p ${SINGULARITY_ROOTFS}/ext

%runscript
  exec /usr/local/miniconda/bin/halfpipe "$@"
  
%startscript
  exec /usr/local/miniconda/bin/halfpipe "$@"
