package:
  name: "halfpipe"
  version: '{{ environ["halfpipe_version"] }}'

source:
  git_url: ../..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python
    - pip
    - setuptools_scm>=6.2
    - wheel
  run:
    - python
    - ants
    - rmath
    - nipype>=1.8.1
    - fmriprep==25.2.3
    - smriprep
    - niworkflows
    - sdcflows
    - nibabel>=4.0.0
    - templateflow
    - pybids
    - openneuro-py
    - numpy>=1.20
    - scipy>=1.8.2
    - numba
    - pandas>=1.2.0
    - patsy>=0.5.2
    - statsmodels>=0.14
    - tabulate>=0.8.9
    - pint>=0.17
    - datalad
    - matplotlib
    - seaborn>=0.11.1
    - svgutils>=0.3.1
    - odfpy>=1.4.1
    - xlrd>=1.0.0
    - openpyxl>=3.0.7
    - XlsxWriter>=1.4.4
    - flufl.lock>=5.0.3
    - psutil>=5.8.0
    - threadpoolctl
    - fasteners>=0.15
    - chardet
    - pympler>=0.9
    - stackprinter>=0.2.5
    - line_profiler>=4.0.1
    - pyrsistent>=0.18.1
    - requests>=2.25.1
    - inflect>=5.3.0
    - inflection>=0.5.1
    - parse>=1.19.0
    - marshmallow>=3.10.0
    - marshmallow-oneofschema
    - marshmallow-dataclass>=8.5.3
    - marshmallow-enum
    - more-itertools>=8.7.0
    - pytest
    - pytest-cov
    - pytest-env
    - pytest-github-actions-annotate-failures
    - pytest-timeout
    - pytest-xdist
    - pytest-forked
    - pytest-rerunfailures
    - python
    - fsl-feat5
    - fsl-film
    - fsl-flameo
    - fmripost_aroma
    - afni-3dtproject
    - afni-3dblurtofwhm
    - afni-3dcalc
    - afni-3dtstat
    - afni-3dreho
    - gica_cmd
    - brainspace
    # New user interface
    - textual
    - pytest-textual-snapshot

test:
  imports:
    - halfpipe
    - halfpipe.logging

about:
  home: https://github.com/HALFpipe/HALFpipe
  summary: "HALFpipe is a user-friendly software that facilitates reproducible analysis of fMRI data"
