{% set name = "halfpipe" %}
{% set version = "4f8396c73523239e004bf2f320f4e76b626c0dea" %}

# Dependencies derived from:
# requirements.in

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/HALFpipe/HALFpipe.git
  git_rev: "{{ version }}" # will this be a problem?

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python 3.11.*
    - nipype>=1.8.1
    - setuptools_scm>=6.2
    - wheel
    - fmriprep==20.2.7+halfpipe.2
    - smriprep==0.7.2+halfpipe.2
    - niworkflows>=1.3.10
    - sdcflows==1.3.5
    - nibabel>=4.0.0
    - templateflow>=0.7.1
    - pybids>=0.13.1
    - openneuro-py
    - numpy>=1.20
    - scipy>=1.8.2
    - numba
    - pandas>=1.2.0
    - patsy>=0.5.2
    - statsmodels>=0.14
    - tabulate>=0.8.9
    - pint>=0.17
    - datalad
    - matplotlib
    - seaborn>=0.11.1
    - svgutils>=0.3.1
    - odfpy>=1.4.1
    - xlrd>=1.0.0
    - openpyxl>=3.0.7
    - XlsxWriter>=1.4.4
    - flufl.lock>=5.0.3
    - psutil>=5.8.0
    - threadpoolctl
    - fasteners>=0.15
    - chardet
    - pympler>=0.9
    - stackprinter>=0.2.5
    - line-profiler>=4.0.1
    - pyrsistent>=0.18.1
    - requests>=2.25.1
    - inflect>=5.3.0
    - inflection>=0.5.1
    - parse>=1.19.0
    - marshmallow>=3.10.0
    - marshmallow-oneofschema
    - marshmallow-dataclass>=8.5.3
    - marshmallow-enum
    - more-itertools>=8.7.0
    - pytest
    - pytest-cov
    - pytest-env
    - pytest-github-actions-annotate-failures
    - pytest-timeout
    - pytest-xdist

test:
  imports:
    - halfpipe
    - halfpipe.logging

about:
  home: https://www.nipreps.org/fmriprep/
  summary: "Halfpipe"
