{% set version = "0.0.5" %}
{% set name = "niflow-nipype1-workflows" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4df3abd4d1fad60374fbd7b29b98a6c0cda2abb907c9ca571ff92de852818e3c

build:
  number: 0
  script: {{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -vv

requirements:
  host:
    - pip
    - python=3.11.*
  run:
    - python=3.11.*
    - future>=0.18.3
    - nipype

test:
  imports:
    - niflow.nipype1.workflows

about:
  home: https://github.com/niflows/nipype1-workflows
  summary: 'niflow-nipype1-workflows workflow package'
