{% set name = "sdcflows" %}
{% set version = "1.3.5" %}

# Dependencies derived from:
# https://github.com/nipreps/sdcflows/blob/1.3.5/setup.cfg

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/nipreps/sdcflows.git
  git_rev: "{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --default-timeout=100 . --no-deps -v"

requirements:
  host:
    - python 3.11.*
    - pip
  run:
    - python 3.11.*
    - nibabel>=3.0.1
    - niflow-nipype1-workflows #~= 0.0.1
    - nipype #>=1.3.1,<2.0
    - niworkflows #>= 1.2.0,<1.4
    - numpy
    - pybids>=0.10.2
    - templateflow>=0.4

test:
  imports:
    - sdcflows

about:
  home: https://github.com/nipreps/sdcflows
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Susceptibility Distortion Correction Flows - a toolbox for preprocessing magnetic resonance images of the brain."
