name: build

on:
  push:
    branches: 
      - master
  release:
    types:
      - published
      - edited

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up build tag
        id: build_tag
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          env
          VERSION=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)
          if [[ "$VERSION" == "master" ]]; then
            VERSION=latest
          fi
          TAG=$(echo "${GITHUB_REPOSITORY}:${VERSION}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output tag=${TAG}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.build_tag.outputs.tag }}
            ghcr.io/${{ steps.build_tag.outputs.tag }}
