name: continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  test:
    runs-on: self-hosted
    timeout-minutes: 1440 # Set to 24 hours
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          # Check out full history for `setuptools_scm`
          fetch-depth: 0

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v3.2.0
        with:
          condarc: |
            channels:
              - conda-forge
              - https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public
          environment-name: test
          create-args: >-
            awscli
            boto3
            conda-build
            datalad
            loguru
            pygithub
            py-rattler
            pyyaml
            setuptools_scm
            tqdm
          cache-environment: true
          init-shell: bash

      - name: Set up metadata
        id: metadata
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          REGISTRY: ${{ secrets.REGISTRY }}
          PYTHONPATH: "src"
        run: |
          git config --global user.name "halfpipe"
          git config --global user.email "halfpipe@fmri.science"
          python -m build.metadata

      - name: Build Conda packages
        if: ${{ steps.metadata.outputs.run == 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PUSH: ${{ steps.metadata.outputs.push }}
          PYTHONPATH: "src"
        run: |
          datalad get src
          printf '%s' '${{ secrets.MATLAB_LICENSE }}' > ${HOME}/license.lic
          python -m build.conda

      - name: Login to DockerHub
        uses: docker/login-action@v4
        if: ${{ steps.metadata.outputs.push == 'true' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to container registry
        uses: docker/login-action@v4
        if: ${{ steps.metadata.outputs.push == 'true' }}
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        if: ${{ steps.metadata.outputs.run == 'true' }}
        uses: docker/setup-buildx-action@v4
        id: buildx
      - name: Build container
        if: ${{ steps.metadata.outputs.run == 'true' }}
        uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: ${{ steps.metadata.outputs.cache_from }}
          cache-to: ${{ steps.metadata.outputs.cache_to }}
          context: "."
          file: "./Dockerfile"
          labels: |
            ${{ steps.metadata.outputs.labels }}
          load: true
          platforms: linux/amd64
          push: false
          tags: |
            ${{ steps.metadata.outputs.build_tag }}

      - name: Cache data
        if: ${{ steps.metadata.outputs.run == 'true' }}
        uses: actions/cache@v6
        with:
          key: resource-cache
          path: /home/runner/resource-cache
      - name: Setup integration test container
        if: ${{ steps.metadata.outputs.run == 'true' }}
        run: |
          docker run \
            --detach \
            --rm \
            --name="test" \
            --volume="/home/runner/resource-cache:/var/cache/halfpipe" \
            --volume="/home/runner:/home/runner" \
            --volume="$(pwd):/halfpipe" \
            --workdir="/halfpipe" \
            --entrypoint="tail" \
            ${{ steps.metadata.outputs.build_tag }} \
            --follow /dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Freesurfer license
        if: ${{ steps.metadata.outputs.run == 'true' }}
        shell: docker exec test bash -x -e {0}
        run: |
          cat > ${FREESURFER_HOME}/license.txt <<EOF
          halfpipe@fmri.science
          73053
           *C8FMo8yrzcZA
           FSCA7.lDgNIow
           e1n3o06osRFD3qtBRgsTy9f9bQHGOpY/riIUrHoEx5c=
          EOF
      # - name: Run TUI snapshot tests (informational)
      #   continue-on-error: true
      #   shell: docker exec test bash -x -e {0}
      #   env:
      #     GITHUB_ACTIONS: true
      #   run: |
      #     echo "***Running TUI tests (informational)***"
      #     py.test --forked /home/runner/actions-runner/_work/HALFpipe/HALFpipe/tests/tui/snapshot_tests
      # - name: Upload snapshot report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: snapshot-report
      #     path: /home/runner/actions-runner/_work/HALFpipe/HALFpipe/snapshot_report.html
      #     if-no-files-found: ignore
      - name: Run integration tests
        if: ${{ steps.metadata.outputs.run == 'true' }}
        shell: docker exec test bash -x -e {0}
        env:
          # Enable pytest-github-actions-annotate-failures
          GITHUB_ACTIONS: true
        run: |
          # Let git-annex get test resources from within the container
          git config --global --add "safe.directory" "*"
          # Run the integration tests
          py.test -k 'not test_consistency' \
            --cov --cov-report=xml --dist=load \
            --numprocesses=2

      - name: Upload coverage to Codecov
        if: ${{ steps.metadata.outputs.run == 'true' }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
      - name: Stop integration test container
        if: ${{ steps.metadata.outputs.run == 'true' }}
        run: |
          docker kill test

      - name: Push container to registry
        if: ${{ steps.metadata.outputs.push == 'true' }}
        uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: ${{ steps.metadata.outputs.cache_from }}
          context: "."
          file: "./Dockerfile"
          labels: |
            ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.metadata.outputs.push_tags }}

      - name: Set up Apptainer
        if: ${{ steps.metadata.outputs.push == 'true' }}
        run: |
          sudo add-apt-repository --yes "ppa:apptainer/ppa"
          sudo apt install --yes "apptainer"

      - name: Build Apptainer container
        if: ${{ steps.metadata.outputs.push == 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          mkdir "singularity"
          sif_file="./singularity/${{ steps.metadata.outputs.singularity_name }}"
          apptainer build \
            --disable-cache \
            "${sif_file}" \
            "docker-daemon://${{ steps.metadata.outputs.build_tag }}"
          # Check if the container works
          apptainer run --userns "${sif_file}" --help
          # Extract Singularity 2.x container
          simg_file="${sif_file%.sif}.simg"
          data_object_id=$(apptainer sif list "${sif_file}" | awk -F"|" '/Squashfs/ {print $1+0}')
          apptainer sif dump "${data_object_id}" "${sif_file}" > "${simg_file}"
          # Upload the containers
          for file in "${sif_file}" "${simg_file}"; do
            aws s3 mv \
              --acl public-read \
              "${file}" \
              "s3://download-fmri-science/singularity/"
          done
